---
- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - curl
  tags: deps

- name: Install Java7
  apt: pkg=default-jre update_cache=yes state=latest
  tags: deps


- name: Add Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ version }}/debian stable main" state=present

- name: Add Logstash repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash
  apt: pkg=logstash update_cache=yes state=latest

- name: Logstash set heap size
  action: >
     lineinfile dest=/etc/init.d/logstash state=present
     regexp="^LS_HEAP_SIZE="
     line='LS_HEAP_SIZE="{{config.heap_size|int}}m"'
  notify: Restart Logstash

- name: Install logstash configuration files
  template: src=logstash.conf dest=/etc/logstash/conf.d/logstash.conf
  notify: Restart Logstash

- name: Download the latest GeoIP database
  command: "{{item}}"
  with_items:
    - curl -o /etc/logstash/GeoLiteCity.dat.gz "http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
    - gunzip -f /etc/logstash/GeoLiteCity.dat.gz

- name: Install Geoip logstash plugin
  command: /opt/logstash/bin/plugin install logstash-filter-geoip
  notify: Restart Logstash

- name: Install Sphinx logstash plugin
  command: /opt/logstash/bin/plugin install logstash-filter-sphinx
  notify: Restart Logstash

- name: Start Logstash
  service: name=logstash state=started enabled=yes
