---
- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - curl
  tags: deps

- name: Install Java7
  apt: pkg=default-jre update_cache=yes state=latest
  tags: deps

- name: Add Elasticsearch repository
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch.version }}/debian stable main" state=present

- name: Add Elasticsearch repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Elasticsearch
  apt: pkg=elasticsearch update_cache=yes state=latest

- name: ES configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: Restart ES

- name: ES set heap size
  action: >
     lineinfile dest=/etc/init.d/elasticsearch state=present
     regexp="^ES_HEAP_SIZE" insertafter="\#ES_HEAP_SIZE"
     line="ES_HEAP_SIZE={{elasticsearch.config.heap_size|int}}m"
  notify: Restart ES

- name: Start ES
  service: name=elasticsearch state=started enabled=yes

- name: Wait for ES to start
  wait_for: host=127.0.0.1 port=9200

- name: Prepare template directory
  file: path=/etc/elasticsearch/templates state=directory owner=root group=root mode=0755

- name: Load template
  template: src=sphinx.template.json dest=/etc/elasticsearch/templates/sphinx.json


- name: Install the 'head' plugin
  command: "/usr/share/elasticsearch/bin/plugin -i mobz/elasticsearch-head"
  ignore_errors: yes
